CC = gcc
CFLAGS = -Wall -O0 -std=c11


main:
	 $(CC) $(CC_FLAGS) main.c -o output
	./output tytul
	make clean

send:
	$(CC) $(CC_FLAGS) main.c -o output
	./output adrianryt TestTytul9 WItamSerdeczne
	make clean
clean:
	rm -f *output*